### ISSUE TITLE
linux compile

### ISSUE THREAD

**Issue by christinazavou** [Forceflow/gpu_suggestive_contours#1]
Hello, thanks a lot for sharing this code! I'm new to C++ and I've been trying to use this rtsc library with trimesh and glui on linux but i'm running into various issues! I see this repo is more up-to-date than the original code (!) so I'm wondering if you could provide some help on how to compile this on ubuntu for cpu use.

I have generated a folder with this structure:
```
contourcode:
    include  
        trimesh2 // contains the same header files as in gpu_suggestive_contours/src/legacy_OpenGL/cpu_objectbased/include/trimesh2
            GL // contains the same header files as in gpu_suggestive_contours/src/legacy_OpenGL/cpu_objectbased/include/trimesh2/GL
    src  // contains same source and header files as in // contains the same header files as in gpu_suggestive_contours/src/legacy_OpenGL/cpu_objectbased/src
    main_viewer.cc  // same file content as gpu_suggestive_contours/src/sc_viewer/src/mesh_view.cc
    CMakeLists.txt
```

where CMakeLists.txt contains
```
cmake_minimum_required(VERSION 3.17)
project(contourcode)

set(CMAKE_CXX_STANDARD 14)
set(EXECUTABLE contourapp)

include_directories(
        include/trimesh2
        include/trimesh2/GL
)
file(GLOB HEADERS "*.h" "include/trimesh2/*.h" "include/trimesh2/GL/*.h" "src/*.h")
file(GLOB SOURCES "*.cc" "src/*.cpp" "src/*.cc")
message("HEADERS: ${HEADERS}")
message("SOURCES: ${SOURCES}")
add_executable(${EXECUTABLE}
        ${HEADERS}
        ${SOURCES})
```

If i run the following commands
```
mkdir build
cd build
cmake ..
make
```

make fails with 

```
/../contourcode/main_viewer.cc:17:10: fatal error: GLManager.h: No such file or directory
 #include "GLManager.h"
          ^~~~~~~~~~~~~
compilation terminated.
CMakeFiles/contourapp.dir/build.make:81: recipe for target 'CMakeFiles/contourapp.dir/main_viewer.cc.o' failed
make[2]: *** [CMakeFiles/contourapp.dir/main_viewer.cc.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/contourapp.dir/all' failed
make[1]: *** [CMakeFiles/contourapp.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
```

i.e. looks to be missing a GLManager definition ... and I'm wondering how can you run mesh_view.cc with
```
void initGL()
{
    gl.make_shader("unlit", unlit_vert, unlit_frag);
    gl.make_shader("phong", phong_vert, phong_frag);
    gl.make_shader("flat", flat_vert, flat_frag);
    if (gl.slow_tstrips())
        avoid_tstrips = true;
}
```
since make_shader that should be defined in GLManager.h is not declared anywhere ... 
am I missing something?

Thanks in advance :)

**Comment by Forceflow** [comment]
I see how this happened - you're still compiling with the old TriMesh version that was included in the cpu_viewer folder.
My bad, I can see how this is confusing.

Make sure you're using a newer Trimesh2 version, as can be found here: https://github.com/Forceflow/trimesh2

Newer versions include GL_manager. To avoid this confusion in the future, I'll remove that include folder from the repo.

**Comment by Forceflow** [comment]
Got rid of the confusing include in f55e927945ba67666ff73752ebfbe80b0a6fc40e

**Comment by christinazavou** [comment]
Great thanks :)

However I still can't get it running ... it gives me some "multiple definition" messages like
```
CMakeFiles/contourapp.dir/src/Viewer.o:(.bss+0x40): multiple definition of `global_bsph'
CMakeFiles/contourapp.dir/main_viewer.o:(.bss+0x90): first defined here
CMakeFiles/contourapp.dir/src/Viewer.o:(.bss+0x100): multiple definition of `camera'
CMakeFiles/contourapp.dir/main_viewer.o:(.bss+0x200): first defined here
CMakeFiles/contourapp.dir/src/Viewer.o: In function `cls()':
Viewer.cpp:(.text+0x23): multiple definition of `cls()'
```
as well as many "undefined reference" to gl staff like
```
main_viewer.cc:(.text+0x5936): undefined reference to `glDisable'
main_viewer.cc:(.text+0x5940): undefined reference to `glDisable'
main_viewer.cc:(.text+0x5974): undefined reference to `glClearColor'
main_viewer.cc:(.text+0x59d2): undefined reference to `glClearDepth'
...
FaceContourDrawer.cpp:(.text+0xb6): undefined reference to `glPolygonOffset'
FaceContourDrawer.cpp:(.text+0xc0): undefined reference to `glEnable'
FaceContourDrawer.cpp:(.text+0xca): undefined reference to `glDisable'
```

I'm guessing that the first message is something that has to do with how inheritence works in c++
and the second is something with GL globally on my laptop ?

I've reproduced the error within a docker container as you can see [here](https://github.com/christinazavou/gpu_suggestive_contours/blob/onlaptop/Dockerfile)

Any suggestions would be useful :)

**Comment by Forceflow** [comment]
**Those second set of errors** indicate that your OpenGL headers are not loaded / not available.

Your compiler needs to find references to the OpenGL functionality your system provides. The fact that it can't even find "glDisable" and "glEnable" (both very basic OpenGL calls) makes me believe that your OpenGL headers are not available / loaded. Have you installed libgl / libglew in your OS package manager?

**The first section of errors** makes me believe that you're still including old trimesh files two times somewhere. Make sure you compile trimesh2 beforehand, in a totally different folder/workspace, and only include the header files in this project. Your project will then use the static trimesh2 library. Notice how in my latest commit, everything related to trimesh2 was deleted from the objectspace_cpu source tree. It expects headers and the static lib from an external dependency.

I can see in your docker example how you're installing the right packages, but I'm not sure your Cmake file is correct. I'm not well-versed enough in Cmake to make suggestions, but if I would make a stab at it:

- /include/trimesh doesn't exist anymore, so that won't work
- GLEW is not mentioned / used anywhere in that cmakefile. That seems essential.

**Comment by christinazavou** [comment]
Thanks a lot, indeed i should have specified where those opengl lib files are in my cmakelists.txt, so it worked with the following

```
cmake_minimum_required(VERSION 3.17)
set(CMAKE_CXX_STANDARD 14)

project(contourproject)

set(OPENGL_LIBS_DIR /usr/lib/x86_64-linux-gnu)
SET(OPENGL_LIBS "libGL.so libglut.so libGLEW.so libEGL.so")

set(VIEWER_EXE ViewerApp)
set(RENDER_EXAMPLE_EXE RenderExampleApp)

include_directories(
        include/trimesh2
        include/trimesh2/GL
)
file(GLOB HEADERS
        "include/trimesh2/GL/*.h"
        "include/trimesh2/*.h"
        "src/*.h"
        "mysrc/*.h")
message("HEADERS: ${HEADERS}")

file(GLOB SOURCES
        "src/trimesh2/libsrc/*.cc"
        "src/trimesh2/libsrc/*.inc"
        "src/trimesh2/utilsrc/*.inc"
        "src/*.cpp"
        "src/*.cc")
message("SOURCES: ${SOURCES}")

link_directories(${OPENGL_LIBS_DIR})

add_executable(${VIEWER_EXE}
        ${HEADERS}
        ${SOURCES}
        "src/runners/Viewer.cpp")
target_link_libraries(${VIEWER_EXE} libGL.so libglut.so libGLEW.so)

add_executable(${RENDER_EXAMPLE_EXE}
        ${HEADERS}
        ${SOURCES}
        "src/runners/renderexample.cpp")
target_link_libraries(${RENDER_EXAMPLE_EXE} libGL.so libglut.so libGLEW.so libEGL.so)
```

**Comment by Forceflow** [comment]
Feel free to make  PR with that cmake file, it's better than nothing, might save someone else some hours of work ;)
